### ISSUE TITLE
Error in bugsack 

### ISSUE THREAD

**Issue by addonaddict** [kemayo/wow-handynotes-lorewalkers#1]
1x HandyNotes_Lorewalkers\Lore.lua:250: GetAchievementCriteriaInfo(achievementID, criteriaIndex [,countHidden]), criteria not found
[string "=[C]"]: ?
[string "@HandyNotes_Lorewalkers\Lore.lua"]:250: in function `(for generator)'
[string "@HandyNotes\HandyNotes-v1.6.1.lua"]:433: in function `UpdateMinimapPlugin'
[string "@HandyNotes\HandyNotes-v1.6.1.lua"]:492: in function `?'
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `SendMessage'
[string "@HandyNotes_Lorewalkers\Lore.lua"]:327: in function `?'
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@DataStore\libs\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by kemayo** [comment]
I don't see this happening. Can I get a little context about when you saw it?

**Comment by addonaddict** [comment]
Sorry im not sure as it happened sometime in the span of 10-15m of me being in isle of thunder in between ui /reloads
If i get it again I will let you know more precisely, I was hoping the error alone would be enough

**Comment by addonaddict** [comment]
Update - I just entered "blood in the snow" heroic scenario from vale and got the error
Hope this helps track it down better

8x HandyNotes_Lorewalkers\Lore.lua:250: GetAchievementCriteriaInfo(achievementID, criteriaIndex [,countHidden]), criteria not found
[string "=[C]"]: ?
[string "@HandyNotes_Lorewalkers\Lore.lua"]:250: in function `(for generator)'
[string "@HandyNotes\HandyNotes-v1.6.1.lua"]:433: in function `UpdateMinimapPlugin'
[string "@HandyNotes\HandyNotes-v1.6.1.lua"]:492: in function `?'
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `SendMessage'
[string "@HandyNotes_Lorewalkers\Lore.lua"]:327: in function `?'
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@DataStore\libs\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by kemayo** [comment]
I can't reproduce this still, but I can add in some defensive code around where the error is happening and see if that helps...

**Comment by kemayo** [comment]
Could you update to the new alpha and let me know if you're still seeing the error?
