### ISSUE TITLE
The Emperor's Burden - part 6 is missing 

### ISSUE THREAD

**Issue by addonaddict** [kemayo/wow-handynotes-lorewalkers#2]
Hi,

I noticed "The Emperor's Burden - part 6" is missing from the map despite me not having the achievment for it
https://www.wowhead.com/object=213443/the-emperors-burden-part-6#

Not sure if this is some bug that's only related to me but just thought id leave it here

Thanks

**Comment by kemayo** [comment]
Oh, that's there, but it looks like it's mislabeled as part 4. I'll fix that.
