### ISSUE TITLE
Lore.lua:49: attempt to call global 'GetPOITextureCoords' (a nil value)

### ISSUE THREAD

**Issue by Ookami313** [kemayo/wow-handynotes-lorewalkers#4]
Zoned into Pandaria to turn in the time walking quest item at the Timeless Isle and I received the following error. Thanks.

6x Interface/AddOns/HandyNotes_Lorewalkers/Lore.lua:49: attempt to call global 'GetPOITextureCoords' (a nil value)
[string "@Interface/AddOns/HandyNotes_Lorewalkers/Lore.lua"]:49: in function <Interface/AddOns/HandyNotes_Lorewalkers/Lore.lua:37>
[string "@Interface/AddOns/HandyNotes_Lorewalkers/Lore.lua"]:261: in function `(for generator)'
[string "@Interface/AddOns/HandyNotes/HandyNotes.lua"]:443: in function <Interface/AddOns/HandyNotes/HandyNotes.lua:429>
[string "=[C]"]: ?
[string "@Interface/AddOns/HandyNotes/HandyNotes.lua"]:56: in function <Interface/AddOns/HandyNotes/HandyNotes.lua:51>
[string "@Interface/AddOns/HandyNotes/HandyNotes.lua"]:493: in function `?'
[string "@Interface/AddOns/AllTheThings/lib/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:119: in function <...ings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface/AddOns/AllTheThings/lib/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:29: in function <...ings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Interface/AddOns/AllTheThings/lib/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface/AddOns/SilverDragon/lib/HereBeDragons/HereBeDragons-2.0-22.lua"]:310: in function <...SilverDragon/lib/HereBeDragons/HereBeDragons-2.0.lua:293>
[string "@Interface/AddOns/SilverDragon/lib/HereBeDragons/HereBeDragons-2.0-22.lua"]:340: in function <...SilverDragon/lib/HereBeDragons/HereBeDragons-2.0.lua:339>

**Comment by kemayo** [comment]
I moved everything in this into [HandyNotes: Mists of Pandaria](https://www.curseforge.com/wow/addons/handynotes_lostandfound). I don't mind fixing this to run, but it's suuuuuper low priority for me now. :D

**Comment by Ookami313** [comment]
Great, thanks for the info. I think I have both, so I guess I've been playing with an addon that was not needed. :D I'll just drop Lorewalkers since if it's been incorporated into HN: MoP it's not needed anymore. Thanks again.

**Comment by kemayo** [comment]
There are a couple of Pandaria ones out there, so I can only promise that this'll be present if you've got the specific one I linked to. 😉

**Comment by Ookami313** [comment]
Yea, that's not an issue since I have all of your HN modules even if I don't use them all the time, by which thanks for all the work you've done with these. Just grabbed up v1 of the Dragon Isles so one more added. 😉
